sudo: false

language: node_js
node_js:
  - 8.5.0

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox
cache:
  directories:
  - node_modules # NPM packages

script:
  - npm run build

deploy:
  provider: npm
  email: supermanchc@gmail.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
  on:
    tags: true

